- name: add tmpfs to fstab
  blockinfile:
    path: /etc/fstab
    block: |
      tmpfs        /home/pi/bOS    tmpfs   nosuid,nodev         0       0

- name: link updater systemd service
  file:
    state: link
    src: /home/pi/bbox/systemd/updater.service
    dest: /etc/systemd/system/updater.service

- name: link server systemd service
  file:
    state: link
    src: /home/pi/bbox/systemd/server.service
    dest: /etc/systemd/system/server.service

- name: enable updater systemd service
  systemd:
    state: started
    enabled: yes
    name: updater

- name: enable server systemd service
  systemd:
    state: started
    enabled: yes
    name: server
