- name: install uuid-runtime
  apt:
    name:
    - uuid-runtime
    state: present

- name: install alsa-packages
  apt:
    name:
    - alsa-utils
    state: present

- name: link updater systemd service
  file:
    state: link
    src: /home/pi/bbox/systemd/updater.service
    dest: /etc/systemd/system/updater.service

- name: link rtc systemd service
  file:
    state: link
    src: /home/pi/bbox/systemd/hwclock.service
    dest: /etc/systemd/system/hwclock.service

- name: link bhive systemd service
  file:
    state: link
    src: /home/pi/bbox/systemd/bhive.service
    dest: /etc/systemd/system/bhive.service

- name: link server systemd service
  file:
    state: link
    src: /home/pi/bbox/systemd/server.service
    dest: /etc/systemd/system/server.service

- name: enable updater systemd service
  systemd:
    state: stopped
    enabled: yes
    name: updater

- name: enable rtc systemd service
  systemd:
    state: stopped
    enabled: yes
    name: hwclock

- name: enable server systemd service
  systemd:
    state: stopped
    enabled: yes
    name: server

- name: set hostname
  hostname:
    name: bbox

- name: make hostname resolvable
  lineinfile:
    path: /etc/hosts
    line: 127.0.0.1 bbox

- name: install avahi-daemon
  apt:
    name:
    - avahi-daemon
    state: present

- name: install utilities
  apt:
    name:
    - python3-distutils
    state: present


- name: configure eth0
  copy:
    dest: /etc/systemd/network/eth0.network
    mode: 0644
    owner: root 
    group: root
    content: |
      [Match]
      Name=eth0

      [Network]
      Address=192.168.233.1/24

- name: enable systemd-networkd
  systemd:
    state: stopped
    enabled: yes
    name: systemd-networkd

- name: install dhcpd
  apt:
    name:
    - isc-dhcp-server
    state: present

- name: configure dhcpd
  copy:
    dest: /etc/dhcp/dhcpd.conf
    mode: 0644
    owner: root 
    group: root
    content: |
      option domain-name "bbox";
      default-lease-time 600;
      max-lease-time 7200;
      ddns-update-style none;
      authoritative;

      subnet 192.168.233.0 netmask 255.255.255.0 {
        range 192.168.233.10 192.168.233.100;
      }

- name: set interface for dhcp server
  lineinfile:
    path: /etc/default/isc-dhcp-server
    line: INTERFACESv4="eth0"
    state: present

- name: active w1-gpio service
  lineinfile:
    path: /boot/config.txt
    line: dtoverlay=w1-gpio,gpiopin=17

- name: install i2c-tools
  apt:
    name:
    - i2c-tools
    state: present

- name: update config.txt
  blockinfile:
    path: /boot/config.txt
    block: |
      dtparam=i2c_arm=on
#       dtoverlay=i2c-rtc-gpio,ds1339,i2c_gpio_sda=2,i2c_gpio_scl=3,wakeup-source

- name: enable i2c module
  lineinfile:
    path: /etc/modules-load.d/modules.conf
    line: i2c-bcm2708

- name: enable i2c-dev module
  lineinfile:
    path: /etc/modules-load.d/modules.conf
    line: i2c-dev

- name: copy rtc setup file
  copy:
    src: setup_rtc.sh
    dest: /usr/local/sbin/setup_rtc.sh
    mode: '0755'

- name: set timezone to UTC
  timezone:
    name: Etc/UTC

- name: create uuid
  ansible.builtin.command: "uuidgen | tee /home/pi/.queensaver_registration_id"
  register: uuid
  tags: uuid

- name: output uuid
  debug:
    var: uuid.stdout_lines
  tags: uuid
