
- name: link updater systemd service
  file:
    state: link
    src: /home/pi/bbox/systemd/updater.service
    dest: /etc/systemd/system/updater.service

- name: link bhive systemd service
  file:
    state: link
    src: /home/pi/bbox/systemd/bhive.service
    dest: /etc/systemd/system/bhive.service

- name: link server systemd service
  file:
    state: link
    src: /home/pi/bbox/systemd/server.service
    dest: /etc/systemd/system/server.service

- name: enable updater systemd service
  systemd:
    state: stopped
    enabled: yes
    name: updater

- name: enable server systemd service
  systemd:
    state: stopped
    enabled: yes
    name: server

- name: set hostname
  hostname:
    name: bbox

- name: make hostname resolvable
  lineinfile:
    path: /etc/hosts
    line: 127.0.0.1 bbox

- name: configure eth0
  copy:
    dest: /etc/network/interfaces.d/eth0
    mode: 0644
    owner: root 
    group: root
    content: |
      auto eth0
      iface eth0 inet static
      address 192.168.233.1
      netmask 255.255.255.0

- name: install dhcpd
  apt:
    name:
    - isc-dhcp-server
    state: present

- name: configure dhcpd
  copy:
    dest: /etc/dhcp/dhcpd.conf
    mode: 0644
    owner: root 
    group: root
    content: |
      option domain-name "bbox";
      default-lease-time 600;
      max-lease-time 7200;
      ddns-update-style none;
      authoritative;

      subnet 192.168.233.0 netmask 255.255.255.0 {
        range 192.168.233.10 192.168.233.100;
      }

- name: set interface for dhcp server
  lineinfile:
    path: /etc/default/isc-dhcp-server
    line: INTERFACESv4="eth0"
    state: present

- name: active w1-gpio service
  lineinfile:
    path: /boot/config.txt
    line: dtoverlay=w1-gpio,gpiopin=17
