- name: create wittypi directory
  file:
    path: /etc/wittypi
    state: directory
    owner: root

- name: Copy Witty init files
  copy:
    src: '{{item}}'
    dest: '/etc/init.d'
    owner: root
    group: root
    mode: 0755
  loop:
    - wittypi

- name: Copy Witty files
  copy:
    src: '{{item}}'
    dest: '/etc/wittypi'
    owner: root
    group: root
    mode: 0755
  loop:
    - syncTime.sh
    - utilities.sh
    - daemon.sh

- name: install i2c-tools and wiringpi
  apt:
    name:
    - i2c-tools
    - wiringpi
    state: present

- name: enable the witty daemon
  sysvinit:
    name: wittypi
    enabled: yes

- name: enable core frequency
  lineinfile:
    path: /boot/config.txt
    line: core_freq=250

- name: enable i2c kernel feature
  lineinfile:
    path: /boot/config.txt
    line: dtparam=i2c1=on

- name: enable i2c kernel arm feature
  lineinfile:
    path: /boot/config.txt
    line: dtparam=i2c_arm=on

- name: enable i2c module
  lineinfile:
    path: /etc/modules-load.d/modules.conf
    line: i2c-bcm2708

- name: enable i2c-dev module
  lineinfile:
    path: /etc/modules-load.d/modules.conf
    line: i2c-dev
