- name: create wittypi directory
  file:
    path: /etc/witty
    state: directory
    owner: root

- name: Copy Witty files
  copy:
    src: '{{item}}'
    dest: '/etc/witty'
    owner: root
    group: root
    mode: 0755
  loop:
    - syncTime.sh
    - utilities.sh


- name: install i2c-tools
  apt:
    name:
    - i2c-tools
    state: present

- name: enable i2c kernel feature
  lineinfile:
    path: /boot/config.txt
    line: dtparam=i2c_arm=on

- name: enable i2c module
  lineinfile:
    path: /etc/modules-load.d/modules.conf
    line: i2c_dev
