# Todo: Run command to set filesystem read / write 
# sets up the smart socket for the system.

- name: remount fs rw
  command: "mount -o remount,rw /"

- name: set permissions of tmp
  file:
    path: /tmp
    state: directory
    mode: 01777

- name: Copy socket files
  copy:
    src: '{{item}}'
    dest: '/home/pi'
    owner: pi
    mode: 0755
  loop:
    - capture.sh
    - hw.py
    - light_off.sh
    - light_on.sh
    - move.sh
    - index.html
    - poweroff.py
    - calibration.py
    - hx711.py

- name: Copy socket files part 2
  copy:
    src: '{{item}}'
    dest: '/etc/systemd/system'
    owner: root
  loop:
    - server.service
    - bhive.service

- name: restart bbox service
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    name: server

- name: restart avahi service
  ansible.builtin.systemd:
    state: restarted
    name: avahi-daemon

- name: set hostname
  hostname:
    name: smart-socket

- name: make hostname resolvable
  lineinfile:
    path: /etc/hosts
    line: 127.0.0.1 smart-socket

# DONE!
- name: remount fs ro
  command: "mount -o remount,ro /"
