# Todo: Run command to set filesystem read / write 
# sets up the smart socket for the system.
- name: set permissions of tmp
  file:
    path: /tmp
    state: directory
    mode: 01777

- name: Copy socket files
  copy:
    src: '{{item}}'
    dest: '/home/pi'
    owner: pi
    mode: 0755
  loop:
    - capture.sh
    - hw.py
    - light_off.sh
    - light_on.sh
    - move.sh
    - index.html

- name: Copy socket files part 2
  copy:
    src: '{{item}}'
    dest: '/etc/systemd/system'
    owner: root
  loop:
    - server.service
    - bhive.service

- name: restart bbox service
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    name: server

- name: set hostname
  hostname:
    name: smart-socket



