# instructions from: https://medium.com/swlh/make-your-raspberry-pi-file-system-read-only-raspbian-buster-c558694de79
- name: fstab ro append to vfat
  lineinfile:
    regexp: '^(.*vfat\s+defaults)(\s+.*)$'
    line: '\1,ro\2'
    path: /etc/fstab
    backrefs: yes

- name: fstab ro append to ext4
  lineinfile:
    regexp: '^(.*ext4\s+defaults,noatime)(\s+.*)$'
    line: '\1,ro\2'
    path: /etc/fstab
    backrefs: yes

- name: remove unnecessary packages
  apt:
    name:
    - triggerhappy
    - logrotate
    - dphys-swapfile
    - rsyslog
    state: absent
    purge: yes
    # TODO: add back in.
    # update_cache: yes
    autoremove: yes

- name: Disable swap and filesystem check and set it to read-only
  lineinfile:
    regexp: '^(.*)rootwait$'
    line: '\1 rootwait fastboot noswap ro'
    path: /boot/cmdline.txt
    backrefs: yes

- name: install busybox-syslogd
  apt:
    name:
    - busybox-syslogd
    state: present


# Update the file /etc/fstab and add the ,ro flag to all block devices. The updated file should look like this:
# proc                  /proc     proc    defaults             0     0
# PARTUUID=fb0d460e-01  /boot     vfat    defaults,ro          0     2
# PARTUUID=fb0d460e-02  /         ext4    defaults,noatime,ro  0     1
# Also add the entries for the temporary file system at the end of the file:
# tmpfs        /tmp            tmpfs   nosuid,nodev         0       0
# tmpfs        /var/log        tmpfs   nosuid,nodev         0       0
# tmpfs        /var/tmp        tmpfs   nosuid,nodev         0       0
#
# $ sudo rm -rf /var/lib/dhcp /var/lib/dhcpcd5 /var/spool /etc/resolv.conf
# $ sudo ln -s /tmp /var/lib/dhcp
# $ sudo ln -s /tmp /var/lib/dhcpcd5
# $ sudo ln -s /tmp /var/spool
# $ sudo touch /tmp/dhcpcd.resolv.conf
# $ sudo ln -s /tmp/dhcpcd.resolv.conf /etc/resolv.conf
#
# $ sudo rm /var/lib/systemd/random-seed
# $ sudo ln -s /tmp/random-seed /var/lib/systemd/random-seed
#
# Edit the service configuration file /lib/systemd/system/systemd-random-seed.service to have the file created on boot. Add the line ExecStartPre=/bin/echo "" >/tmp/random-seed under the [Service] section.
# The modified [Service] section should look like this:
# [Service]
# Type=oneshot
# RemainAfterExit=yes
# ExecStartPre=/bin/echo "" >/tmp/random-seed
# ExecStart=/lib/systemd/systemd-random-seed load
# ExecStop=/lib/systemd/systemd-random-seed save
# TimeoutSec=30s
